# DEVICE NAME
DEVICE = 'P1S1'
FACILITY = 'SLW'

# PLC INTEGRATION
PLC = False

# PLC IP ADDRESS
PLCIP = '10.152.226.70'

# PLC TAG TO READ RECIPE
PLCTAG = 'B10[7]'
# USE THIS WHEN -PLC- IS FALSE
RECIPE = 31
# RESOLUTION MANAGER
RATIO = 1
# DEVELOPEtR MODE AND FRAMES SKIP
DEVMODE = False
DEVFRAME = 0

# NOTIFICATIONS
WHATSAPP = 'OFF'
SHEETS = 'OFF'

# IMAGE SIZE
IMGSIZE = [1280, 720]

# DISTANCE FORMULA
PIXELINCHX = 7.145225379
PIXELINCHY = 8.359170769

# STANDBY TIME IN SECONDS
SLEEP = 60

# TIMER TIME IN SECONDS
TIMER = 60

# BLANK URL TEMPLATES
BLANK_URL = './templates/blank'

# SLIDECAR URL TEMPLATES
CAR_URL = './templates/car'

# LINE THICKNESS FOR MEASURES
LTHICK_MES = 10
# LINE THICKNESS FOR CAR REFERENCES
LTHICK_CAR = 2
# LINE THICKNESS FOR BLANK DETECTED RECTANGLE
LTHICK_REC = 1
# CIRCLE SIZE FOR REFERENCE POINTS IN DETECTED RECTANGLE
COPEN_REC = 30
CTHICK_MES = 2


# CROP POINTS FOR --BLANK-- DETECTION REGION OF INTEREST
ROIBLANKXMIN = int(400*RATIO)
ROIBLANKXMAX = int(900*RATIO)
ROIBLANKYMIN = int(150*RATIO)
ROIBLANKYMAX = int(630*RATIO)

# CROP POINTS FOR --EMPTY-- DETECTION REGION OF INTEREST
ROIEMPTYXMIN = int(450*RATIO)
ROIEMPTYXMAX = int(710*RATIO)
ROIEMPTYYMIN = int(230*RATIO)
ROIEMPTYYMAX = int(420*RATIO)

# CROP POINTS FOR --SLIDECAR UP-- DETECTION REGION OF INTEREST
ROICUPXMIN = int(300*RATIO)
ROICUPXMAX = int(550*RATIO)
ROICUPYMIN = int(450*RATIO)
ROICUPYMAX = int(600*RATIO)

# CROP POINTS FOR --SLIDECAR DOWN-- DETECTION REGION OF INTEREST
ROICDOWNXMIN = int(600*RATIO)
ROICDOWNXMAX = int(900*RATIO)
ROICDOWNYMIN = int(570*RATIO)
ROICDOWNYMAX = int(850*RATIO)

# COLORS
GREEN = (0, 255, 0)
RED = (200, 0, 0)
BLUE = (0, 0, 255)
BLUE_L = (0, 255, 255)
PINK = (255, 0, 255)
YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (120, 120, 120)


CANNY1 = 100
CANNY2 = 100
LEN_DIV = 5
GAP_DIV = 5

HOUT = 1
HOU1 = 10
HOU2 = 5
###
TEMPSENSE_TM = 0.8
TEMPSENSE_EM = 0.7
TEMPSENSE_CA = 0.7
TEMPSENSE_BL = 0.7

BLANKSHOT = 0
EMPTYSHOT = 0
UPSHOT = 0
DOWNSHOT = 0

FPS = 12
PERSP = 10
FLIP = 0
GSTREAM = False
MEASURENORM = 12
PILEMODENORM = 100
DIFER = -20
SLOPEMIN = -0.5
SLOPEMAX = 0.0

SHOWPIXELS = True